### ISSUE TITLE
Could you please make another release to nuget?

### ISSUE THREAD

**Issue by cli00004** [dynatrace-oss/opentelemetry-metric-dotnet#33]
There is an issue with the max value in the histogram in 0.4.0, it sets the max to 1000 all the time, the latest code seem to have fixed it
![image](https://user-images.githubusercontent.com/94087985/172774615-0fe7b90f-4b88-4489-9598-5a0dc5654609.png)

**Comment by pirgeo** [comment]
Hi, thank you for reaching out. We are currently working on the new version, and will release it soon!

**Comment by pirgeo** [comment]
Hi, we have released a new version on Nuget (https://www.nuget.org/packages/Dynatrace.OpenTelemetry.Exporter.Metrics/1.0.0)! Please do not hesitate to reopen this issue if the new release does not fix the problem.
