### ISSUE TITLE
ILoggerFactory hard to inject in APS.NET Core

### ISSUE THREAD

**Issue by dominikjeske** [dynatrace-oss/opentelemetry-metric-dotnet#36]
Current implementation of AddDynatraceExporter has ILoggerFactory as input parameter - in sample console app it is easy to use but in ASP.NET Core app having ILoggerFactory in configuration phase is hard to implement. It would be better to get ILogger from container.

**Comment by arminru** [comment]
Hi Dominik!

In 2022, we introduced an OTLP Metrics ingest endpoint in Dynatrace, which makes this exporter here obsolete, as any OTel SDK and the collector can natively export to it out of the box.

You can find more details here:
- https://docs.dynatrace.com/docs/shortlink/send-metrics-via-otlp-exporter
- https://docs.dynatrace.com/docs/shortlink/migrating-dynatrace-metrics-exporter-otlp-exporter

This exporter is deprecated in favor of the OTLP metrics ingest and as such no new features will be implemented.
